#!/bin/sh

# This file is used for deploying my configs on a "fresh" system.
# "config.scm" requires my guile modules, so the purpose of this file is
# to fetch my guile modules, and run "config.scm" using them.

THIS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MY_GUILE_DIR="$(mktemp --directory)"

git clone --depth 1 \
          "https://gitlab.com/alezost-config/guile.git" \
          "$MY_GUILE_DIR"

GUILE_LOAD_PATH=$MY_GUILE_DIR/modules \
  guile -e main -s "$THIS_DIR/config.scm" --fetch --deploy
