fullscreen
no-ytdl
write-filename-in-watch-later-config
# keep-open=yes
# keep-open-pause=no
# ao=alsa
# vo=xv
volume=80
speed=1.2

# does not work!
background=tiles

# no-osd-bar
# osd-on-seek=no
osd-duration=2000
osd-color='#23B13E'
osd-font='DejaVu Sans:style=Bold'
osd-font-size=50
osd-shadow-offset=2

# Do not display image attachments when playing audio files.
audio-display=no

# Without this option, mpv disables/enables screensaver on every pause.
stop-screensaver=no

# On Screen Controller
osc=no
script-opts=osc-timetotal=yes
